repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.0
    hooks:
      - id: isort
  - repo: https://github.com/ambv/black
    rev: 21.10b0
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
